# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: check file
        run: git show --name-only HEAD
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - uses: actions/checkout@v2
        with:
            # Number of commits to fetch. 0 indicates all history for all branches and tags.
            # Default: 1
            fetch-depth: 2
            run: git ls-tree --name-only -r <commit-ish>

      - name: Print Event Payload
        run: cat $GITHUB_EVENT_PATH
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04LH0JCLQ0,C04KLL2UD70'
          slack-message: "A file named '$FILE_NAME' was committed or pushed to the repository.\nMobile Application Report Link: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url}}"
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

 




