---
name: Deploy_Github_Pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get changed files
        id: getfile
        run: >
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only
          --diff-filter=AM -r ${{ github.sha }} | xargs)"
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: merge notification
        if: steps.getfile.outputs.files != ''
        id: merge_notification
        run: >
          MESSAGES=()

          for file in ${{ steps.getfile.outputs.files }}; do
            if [[ $file == mobile* ]]; then
              FILE_NAME=$(basename "$file")
              MESSAGE="Mobile Application Report Link: https://hasankfz.github.io/mobile-app-reports.github.io/$file"
              echo "Sending message: $MESSAGE"
              MESSAGES+=("$MESSAGE")
            fi
          done

          echo "::set-output name=merged-messages::${MESSAGES[@]}"
      - name: Slack Notify
        if: steps.merge_notification.outputs.merged-messages != ''
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          MESSAGES: ${{ steps.merge_notification.outputs.merged-messages }}
        with:
          channel-id: C04LH0JCLQ0
          slack-message: ${{ steps.merge_notification.outputs.merged-messages}}
