name: Send slack msg

on: 
   push: 
     branches: [master]
   
jobs:

  build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: Notify slack
       env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
       uses: pullreminders/slack-action@master
       with:
           args: '{\"channel\":\"C04L5SXJ3RP\",\"text\":\"The file \`${{github.event.head_commit.message}}\` was pushed to the repository.\"}'
    
    
